//
//  BehaviourBridgeReceptor.h
//
//  Created by Felix Schwarz on 04.06.06.
//  Copyright 2006 IOSPIRIT GmbH. All rights reserved.
//

/*
	LICENSE

	Copyright (c) 2006, IOSPIRIT GmbH ( info@iospirit.com, http://www.iospirit.com/ )
	All rights reserved.

	Redistribution and use in source and binary forms, with or without modification, 
	are permitted provided that the following conditions are met:

	* Redistributions of source code must retain the above copyright notice, this list of 
	  conditions and the following disclaimer.

	* Redistributions in binary form must reproduce the above copyright notice, this list
	  of conditions and the following disclaimer in the documentation and/or other materials 
	  provided with the distribution.
	
	* Neither the name of the IOSPIRIT GmbH nor the names of its contributors may be used
	  to endorse or promote products derived from this software without specific prior written
	  permission.

	THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
	EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
	MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
	THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
	SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
	OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
	HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
	TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
	SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#import <Cocoa/Cocoa.h>
#import "ButtonCodes.h"

@interface BehaviourBridgeReceptor : NSObject 
{
	NSDistributedNotificationCenter	*notificationCenter;
	NSString			*observeName;
	id				delegate;
}

#pragma mark -- Initialization and clean up --
- (id)initWithDelegate:(id)delegate;

#pragma mark -- Accessors --
- (id)delegate;
- (void)setDelegate:(id)newDelegate;

@end

@protocol BehaviourBridgeReceptorDelegate

// If you wanted to use a custom bundle identifier (other than that of your apps bundle),
// this would be the place to "inject" it into BehaviourBridgeReceptor. You can omit this
// delegate method if you want to automatically use the bundle identifier of the app you
// integrate this source code into.
- (NSString *)bundleIdentifier;

// See the behaviour examples for more information on this method
- (void)performForButtonCode:(RemoteButtonCode)buttonCode	// which button was pressed
		  actionCode:(RemoteActionCode)actionCode	// pressed / released
		isAutoRepeat:(BOOL)autoRepeat			// TRUE if the action is generated by a auto repeat function
		    moreInfo:(NSDictionary *)dictionary;	// for future use

// See the behaviour examples for more information on this method
- (void)eventNotification:(RemoteEventCode)eventCode;

@end