//
//  BehaviourProtocol.h
//
//  Created by Felix Schwarz on 24.05.06.
//  Copyright 2006 IOSPIRIT GmbH. All rights reserved.
//

/*
	LICENSE

	Copyright (c) 2006, IOSPIRIT GmbH ( info@iospirit.com, http://www.iospirit.com/ )
	All rights reserved.

	Redistribution and use in source and binary forms, with or without modification, 
	are permitted provided that the following conditions are met:

	* Redistributions of source code must retain the above copyright notice, this list of 
	  conditions and the following disclaimer.

	* Redistributions in binary form must reproduce the above copyright notice, this list
	  of conditions and the following disclaimer in the documentation and/or other materials 
	  provided with the distribution.
	
	* Neither the name of the IOSPIRIT GmbH nor the names of its contributors may be used
	  to endorse or promote products derived from this software without specific prior written
	  permission.

	THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
	EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
	MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
	THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
	SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
	OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
	HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
	TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
	SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#import <Cocoa/Cocoa.h>
#import "ButtonCodes.h"

@protocol Behaviour

#pragma mark -- Should install --
- (BOOL)shouldInstall;						// i.e. check for required resources (applications) here
								//	and only return YES if your behaviour actually will
								//	work on this system. Returning NO will exclude it
								//	from being included into the menu structure

#pragma mark -- Bundle convenience --
- (void)setBundle:(NSBundle *)behaviourBundle;

#pragma mark -- Events receipt --
- (void)performForButtonCode:(RemoteButtonCode)buttonCode	
		  actionCode:(RemoteActionCode)action		// pressed / released
		isAutoRepeat:(BOOL)autoRepeat			// TRUE if the action is generated by a auto repeat function
		    moreInfo:(NSDictionary *)dictionary;	// for future use

- (void)eventNotification:(RemoteEventCode)eventCode;		// in focus, activated, deactivated ..

#pragma mark -- Provide descriptions for what the buttons do -- 
- (NSString *)helpTextForButton:(RemoteButtonCode)buttonCode;	// "Previous track"

#pragma mark -- Menu data --
- (NSString *)title;						// e.g. "TextEdit" - for a behaviour that is aimed at usage for TextEdit
- (NSString *)address;						// e.g. "top.applications" for being in the Applications submenu, there's also top.misc, top.applications, top.system and top.input
- (NSImage *)image;						// e.g. the TextEdit logo

- (BOOL)responsibleForApplicationBundleIdentifier:(NSString *)applicationBundleIdentifier;	// "com.apple.TextEdit"

- (SInt32)backgroundPriorityForApplicationBundleIdentifier:(NSString *)applicationBundleIdentifier; // "com.apple.TextEdit", negative values are higher priorities, see defines below

@end

#define kBehaviourPriorityNone	2048
#define kBehaviourPriorityMin	1024
#define kBehaviourPriorityMax	-1024
